#!name=🏅Spotify + Youtube Predium
#!desc=Mở khoá premium cho ứng dụng Youtube, Spotify
# 💬 Facebook: https://www.facebook.com/quanghuwngg.info
# 🚀 Released by: Nguyễn Quang Hưng
# 👤 Author: QuangHuwngg
#!version= 2.1.4

################################
#         [ Rule ]             #
################################
[Rule]
# --- Youtube Predium ---
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT

[Url Rewrite]
# /Modules/YT-Adblocker.module
# ^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad - reject-img
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad _ reject-200
# ======= Universal Ad Request ======= #
^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads _ reject-200
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) _ reject-200
^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext _ reject-200
# ======= General Video Ad request ======= #
(^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) $1$2$3 302


################################
#        [ Map Local ]         #
################################
[Map Local]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad data-type=text data="" status-code=200


################################
#         [ Header ]           #
################################
[Header Rewrite]
# Spotify fix if none match
http-request ^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ header-del if-none-match


################################
#         [ Script ]           #
################################
[Script]
# --- Youtube Predium ---
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/(youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch))(\?(.*))?$,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/QuangHuwngg/Shadowrocket-Module/refs/heads/main/Resources/Youtube/youtube.response.js,argument="{"lyricLang":"{{{lyricLang}}}","captionLang":"{{{captionLang}}}","blockUpload":"{{{blockUpload}}}","blockImmersive":"{{{blockImmersive}}}","blockShorts":"{{{blockShorts}}}","debug":"{{{debug}}}"}"

# --- Spotify Premium ---
spotify-json = type=http-request,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/QuangHuwngg/Shadowrocket-Module/refs/heads/main/Resources/Spotify/spotify-json.js
spotify-proto = type=http-response,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/QuangHuwngg/Shadowrocket-Module/refs/heads/main/Resources/Spotify/spotify-proto.js,script-update-interval=0


################################
#          [ MITM ]            #
################################
[MITM]
hostname = %APPEND% -redirector*.googlevideo.com,*.googlevideo.com,www.youtube.com,s.youtube.com,youtubei.googleapis.com,api.revenuecat.com,raw.githubusercontent.com,api-mobile.soundcloud.com,spclient.wg.spotify.com,*spclient.spotify.com